apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-python-deployment
  labels:
    app: api-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-python
  template:
    metadata:
      labels:
        app: api-python
    spec:
      containers:
      - name: microservice-api-python
        image: your-username/microservice-python-api:1.0
        ports:
        - containerPort: 3001