apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-nodejs-deployment
  labels:
    app: web-nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-nodejs
  template:
    metadata:
      labels:
        app: web-nodejs
    spec:
      containers:
      - name: microservice-web-nodejs
        image: your-username/microservice-js-web:1.0
        ports:
        - containerPort: 3002
